import { useState } from 'react'
import portada1 from '../../assets/portada-1.webp'
import portada2 from '../../assets/portada-2.webp'
import portada3 from '../../assets/portada-3.webp'
import portada4 from '../../assets/portada-4.webp'
import portada5 from '../../assets/portada-5.webp'
import portada6 from '../../assets/portada-6.webp'
import portada7 from '../../assets/portada-7.webp'
import portada8 from '../../assets/portada-8.webp'
import portada9 from '../../assets/portada-9.webp'
import portada10 from '../../assets/portada-10.webp'
import portada11 from '../../assets/portada-11.webp'
import Nav from '../nav/Nav.js'
import { Outlet } from 'react-router-dom'
import Footer from '../footer/Footer.js'

const Main = () => {
  const [propiedades] = useState(
    [
      {
        name: 'Propiedad en Barrio Fátima, Garupá, Misiones',
        text: 'TERRENO DE 10 POR 30 MTS 2 CON TITULO DE PROPIEDAD E IMPUESTOS AL DÍA EN BARRIO NUEVO FATIMA, GARUPA , SOBRE AVDA. KEMERER  INCLUYE: 1) UNA VIVIENDA FLIAR COMPUESTA POR: DOS DORMITORIOS, BAÑO, COCINA COMEDOR, 2) AMPLIO LOCAL COMERCIAL QUE SE ENCUENTRA JUNTO A LA VIVIENDA 3) EN EL TERRENO HAY UNA CONSTRUCCION A TERMINAR CON ENCADENADO, PAREDES Y PERFILES DE HIERRO DE 30 MTS 2 APROX CON POSIBILIDAD DE HACER UN SEGUNDO PISO; 4) AL FONDO DEL TERRENO HAY UN MONOAMBIENTE DE 10 MTS 2 5) AL COSTADO UN AMBIENTE TECHADO DE 32 MTS2 APROX. DENTRO DEL BARRIO HAY DOS ESCUELAS PRIMARIAS, 1 A UNA CUADRA DE LA VIVIENDA, DOS ESCUELAS SECUNDARIAS A TRES CUADRAS, UN INSTITUTO TERCIARIO A TRES CUADRAS, EL HOSPITAL FATIMA A SEIS CUADRAS, LA COMISARIA DE LA MUJER, SUC  BANCO MACRO, SUPERMERCADOS MAYORISTAS MAKRO, GIMNASIOS, CORRALONES, COMERCIOS DE LA ZONA, COLECTIVOS URBANOS, FACULTAD Y TERMINAL DE LA UNAM A DIEZ CUADRAS',
        portada: portada1,
        vendido: false,
        cantImg: 5
      },
      {
        name: 'Propiedad en Barrio Aguacates, Posadas, Misiones',
        text: 'UBICACIÓN: SOBRE CALLE SARGENTO CABRAL A UNA CUADRA DE AVDA. ROCA, SUPERFICIE REGULAR Y TOTAL: 240 MTS2, MEDIDAS DEL TERRENO: 10 MTS DE FRENTE POR 24 MTS DE FONDO; FACTOR DE OCUPACIÓN DEL SUELO (F.O.S.) EN UN 70 % CUENTA CON UNA AMPLIA VIVIENDA DE TRES HABITACIONES, UN BAÑO, LIVING, COCINA COMEDOR, AMPLIO PATIO TRASERO, QUE OCUPA 80 MTS.2. SE HALLA EMPLAZADO EN EL Bº LOS AGUACATES, QUE ES LA ZONA RESIDENCIAL POR EXCELENCIA DE LA CIUDAD CAPITAL DE LA PROVINCIA DE MISIONES, A 300 MTS DE LA COSTANERA, A SÓLO SIETE CUADRAS DE CENTRO DE LA CIUDAD. CUENTA CON LOS SERVICIOS DE AGUA CORRIENTE, LUZ ELÉCTRICA, ASFALTO, DESAGÜE CLOACAL.- SUS ÍNDICES URBANÍSTICOS SON MÁS QUE DESTACABLES PERMITIENDO EN ALGUNAS DE SUS VARIANTES CONSTRUIR UN EDIFICIO DE PLANTA BAJA Y TRES PISOS. POR UBICACIÓN Y BARRIO HACE QUE SEA UNA ZONA MUY ATRACTIVA PARA VERDADEROS INVERSIONISTAS.- CUENTA CON TODA LA DOCUMENTACIÓN LISTA PARA TRANSFERIR.-',
        portada: portada2,
        vendido: false,
        cantImg: 9
      },
      {
        name: 'Departamento en Zona céntrica de Posadas, Misiones',
        text: 'LA PROPIEDAD ESTA UBICADA EN AVENIDA RADEMACHER AL 5000, CASI AVENIDA CMTE. BUCHARDO, A CINCO MINUTOS DEL MICROCENTRO DE LA CIUDAD DE POSADAS (NO COMPRENDE LOS GASTOS DE COMISION POR VENTA, ESCRITURACION Y DE EXPENSAS, ESTAS INCLUYEN: LIMPIEZA DE ESPACIONS COMUNES, ILUMINACION ELECTRICA DE ESPACIOS COMUNES Y SERVICIO DE AGUA DE ESPACIOS COMUNES). DEPARTAMENTO UBICADO EN PLANTA BAJA DE EDIFICION SOBRE AVENIDA RADEMACHER N° 5475, CONSTA DE DOS HABITACIONES, UN BAÑO, COCINA, UN ESPACIO DE GUARDADO, LIVING COMEDOR, LAVADERO CUBIERTO, PATIO INTERNO, UN PATIO EN GENERAL CON PORTON QUE SE UTILIZA COMO COCHERA. EL DEPARTAMENTO FORMA PARTE DE UNA PRIVILEGIADA INFRAESTRUCTURA EDILICIA ENCLAVADA EN LA ZONA URBANA CENTRICA POSADEÑA POR EXCELENCIA, DONDE LOS PASEOS ARBOLEADOS Y SOMBREADOS FORMAN PARTE DE LA ZONA RESIDENCIAL PROMOCIONADA. EL DEPARTAMENTO A LA VENTA SE ENCUENTRA A ESCASAS CUADRAS DE LA AV COSTANERA DE LA CIUDAD DE POSADAS, EN SUS ALREDEDORES HAY ESTABLECIMIENTOS EDUCATIVOS CERCANOS, ACCESO A VARIAS LINEAS DE TRANSPORTE URBANO DE PASAJERO HACIA TODA LA CIUDAD, ESTA A POCOS MINUTOS DEL MMICROCENTRO, Y CON SALIDA RAPIDA POR ACCESO SUR. CUENTA CON TITULO DE PROPIEDAD E IMPUESTOS AL DIA.',
        portada: portada3,
        vendido: false,
        cantImg: 5
      },
      {
        name: 'Propiedad en Villa Pueblo General Belgrano, Entre ríos',
        text: 'UBICACIÓN: SOBRE CALLE RODOLFO GARCÍA AL 285, ENTRE CALLES 13 DE MARZO Y 30 DE MARZO, VILLA PUEBLO GENERAL BELGRANO, DEPTO GUALEGUAYCHÚ, ENTRE RÍOS, SUPERFICIE REGULAR Y TOTAL: 380 MTS2, MEDIDAS DEL TERRENO: 10 MTS DE FRENTE POR 38 MTS DE FONDO; EN EL TERRENO HAY 2 VIVIENDAS CONSTRUIDAS (ANTIGUEDAD 8 AÑOS). VIVIENDA PRINCIPAL DE 175 M2. CUENTA CON 2 DORMITORIOS, 1 BAÑO, COCINA, ESTAR COMEDOR INTEGRADO, GALERÍA ALREDEDOR DE LA VIVIENDA CUBIERTA, LAVADERO CUBIERTO DENTRO DE UNA GALERÍA TOTALMENTE CERRADA CON DOS VENTANALES, HALL AL FRENTE, A SU COSTADO DERECHO HAY UN SALÓN CON BAÑO SOCIAL DE 17 M2, TECHOS DE CHAPAS DE ZINC, CIELORRASO DE DURLOCK, MUROS INTERIORES Y EXTERIORES DE LADRILLOS, ABERTURAS DE ALUMINIO, SE VENDE CON 3 SPLITS INSTALADOS Y FUNCIONANDO (EN SALA DE ESTAR COMEDOR, DORMITORIO PPAL Y EN GALERÍA CERRADA.) Y VENTILADORES DE TECHO EN TODOS LOS AMBIENTES, FUNCIONANDO. LA SEGUNDA VIVIENDA DE 51, 40 M2., CONSTA DE: 2 DORMITORIOS, 1 BAÑO, COCINA, ESTAR Y COMEDOR INTEGRADO, 1 HABITACIÓN DE DEPÓSITO, GALERÍA CUBIERTA ALREDEDOR DE LA CASA, TECHOS DE CHAPAS DE ZINC, CIELORRASO DE DURLOCK, ABERTURAS DE ALUMINIO, MUROS EXTERIORES E INTERIORES DE LADRILLOS. SE VENDE CON VENTILADORES DE TECHO EN TODOS LOS AMBIENTES, FUNCIONANDO. COCHERA TECHADA PARA 2 VEHÍCULOS. AMBAS CONSTRUCCIONES CUENTAN CON CIMENTACIONES REFORZADAS PARA MITIGAR EL IMPACTO DE FUERTES VIENTOS, CONSTAN DE AGUA CALIENTE POR TERMOFUSIÓN ADEMÁS DE TANQUES DE AGUA, CUENTAN CON TODOS LOS SERVICIOS E ILUMINACIÓN LED INTERIOR EMBUTIDA EN EL TECHO. – UBICADOS A: 800 MTS DE LAS TERMAS DEL GUALEGUAYCHÚ, A 1,5 KM DEL BALNEARIO ÑANDUBAIZAL SOBRE EL RIO URUGUAY, A ESCASOS MTS. DE LA ZONA CÉNTRICA DE GUALEGUAYCHÚ, A 100 MTS DE LAS PARADAS DE COLECTIVOS DE TRANSPORTE PUBLICO DE PASAJEROS, SE ENCUENTRA SITUADA FRENTE A LA CIUDAD DE FRAY BENTOS, REPÚBLICA ORIENTAL DEL URUGUAY.- POR UBICACIÓN Y BARRIO HACE QUE SEA UNA ZONA MUY ATRACTIVA PARA VERDADEROS INVERSIONISTAS.- CUENTA CON TÍTULO DE PROPIEDAD E IMPUESTOS AL DÍA.',
        portada: portada4,
        vendido: false,
        cantImg: 13
      },
      {
        name: 'Propiedad en Zona céntrica de Garupá',
        text: 'UBICADA EN EL BARRIO COMPLEJO GERVASIO ARTIGAS, DE LA LOCALIDAD DE GARUPÁ, PROVINCIA DE MISIONES; SE ENCUENTRA EN VENTA ESTA PRECIOSA VIVIENDA UNIFAMILIAR ARTESANAL CON UN ESTILO RÚSTICO AUTÉNTICO, CON UNA ANTIGUEDAD MENOR A 1 AÑO, CONSTRUIDA COMPLETAMENTE DE TRONCOS DE MADERA DURA DE ALTA CALIDAD, PROPORCIONANDO AISLAMIENTO TÉRMICO NATURAL, UNA VISTA MARAVILLOSA AL EXTERIOR Y UNA ILUMINACIÓN NATURAL DE CALIDAD EN EL INTERIOR. EL TERRENO: ES PLANO Y REGULAR, TIENE 260 MTS² (10 MTS DE FRENTE POR 26 MTS DE FONDO), LA VIVIENDA: TIENE 72 MTS² DE CONSTRUCCIÓN Y 12 MTS² CUBIERTOS DE GALERIA EN CADA PLANTA, DESCRIPCION DE LA CASA: TIENE DOS PLANTAS, DOS DORMITORIOS, COCINA Y COMEDOR INTEGRADO, UN BAÑO TOTALMENTE INSTALADO, MUROS EXTERIORES E INTERIORES: PAREDES DE TRONCO IMPREGNANTE DE MADERA DURA, PISOS REVESTIDOS EN CERÁMICA, TECHO DE CHAPAS DE ZINC. CIELORRASO CON TIRANTERIA DE MADERA A LA VISTA, ABERTURAS: INDUSTRIALIZADAS DE MADERA, ELECTRICIDAD COMPLETA; CUENTA CON CAMARA SÉPTICA, CAMARA DE INSPECCIÓN Y POZO CIEGO PARA COCINA Y PARA BAÑO; AGUA FRÍA Y CALIENTE POR TERMOFUSIÓN, LAVADERO EXTERIOR, PATIO AMPLIO, CON CERRAMIENTO EN TODO EL TERRENO.- CUENTA CON TODOS LOS SERVICIOS: LUZ Y AGUA POTABLE.- SE HALLA UBICADA A 400 MTS DE LA AV. DE LAS AMÉRICAS, DE SUPERMERCADOS, FARMACIAS, A 800 MTS DE LA ZONA CÉNTRICA Y COMERCIAL DE GARUPÁ, A POCOS MTS. DE ESCUELAS PRIMARIA Y SECUNDARIA, ESTÁ EMPLAZADA EN UNA ZONA CON MUCHA ILUMINACIÓN Y VENTILACIÓN NATURAL, RODEADA DE NATURALEZA, CONFORT SENCILLO Y AROMAS SUAVES.- VALOR DE VENTA: 43.000 DÓLARES TÍTULO DE PROPIEDAD E IMPUESTOS AL DÍA',
        portada: portada5,
        vendido: false,
        cantImg: 9
      },
      {
        name: 'Lotes en Candelaria, Misiones',
        text: 'TITULO E IMPUESTOS AL DIA A 350 METROS DE LA COSTA DEL RIO PARANA EN CANDELARIA ESTAN A LA VENTA LOS DOS JUNTOS Y TAMBIEN CADA UNO POR SEPARADO LISTO PARA ESCRITURAR A ESCASOS METROS DE LA RUTA NACIONAL N12 IDEAL PARA INVERSIONISTAS, EMPRENDEDORES O QUIENES AMEN DISFRUTAR DE LA NATURALEZA CADA LOTE FORMA UN TERRENO REGULAR.-',
        portada: portada6,
        vendido: false,
        cantImg: 3
      },
      {
        name: 'Propiedad tipo Chalet en Zona céntrica de San Vicente',
        text: 'INMUEBLE UBICADO SOBRE CALLE ASFALTADA, A ESCASOS METROS DEL COMPLEJO POLIDEPOTIVO MUNICIPA “VERON GALLARDO” Y DEL CLUB “EX ALUMNOS”, EN LA LOCALIDAD DE SAN VICENTE, PROVINCIA DE MISIONES.- MEDIDAS DEL INMUEBLE A TITULO INFORMATIVO: 17 MTS DE FRENTE POR 30 MTS DE FONDO.- TIENE TITULO DE PROPIEDAD, LISTA PARA ESCRITURAR.- CONSTA DE: UNA VIVIENDA UNIFAMILIAR TIPO CHALET DE 12 MTS POR 9 MTS., CONSTA DE:HALL DE ENTRADA, 2 DORMITORIOS, COCINA Y COMEDOR INTEGRADO, LIVING, UN BAÑO, GARAGE, LAVADERO CUBIERTO, TECHO DE CHAPAS DE ZINC, CIELORRASO DE MACHIMBRE, MUROS INTERIORES DE LADRILLOS, ABERTURAS DE ALUMINIO Y DE MADERA. CERRAMIENTO EN TODO EL INMUEBLE.- DOS DEPARTAMENTOS DE 3.80 MTS POR 6,10 MTS CADA UNO, MONOAMBIENTE, CON UN BAÑO.- TAMBIEN TIENE CONSTRUIDO SOBRE LOS DOS MONOAMBIENTES UNA EXCELENTE LOSA QUE MIDE 7,60 MTS POR 6.10 MTS DEAL TODO DESTINO.- CUENTAN CON TODOS LOS SERVICIOS.- VALOR DEL INMUEBLE: 55.000 DOLARES ESTADOUNIDENSES',
        portada: portada7,
        vendido: false,
        cantImg: 12
      },
      {
        name: 'Propiedad con terreno en Zona céntrica de San Vicente',
        text: 'INMUEBLE UBICADO EN PLENO CENTRO DE LA LOCALIDAD DE SAN VICENTE, PROVINCIA DE MISIONES (SOBRE CALLE MARIANO MORENO Y COLECTORA, CON SALIDA POR AMBOS LADOS). MEDIDAS DEL INMUEBLE A TITULO INFORMATIVO: 35.21MTS X 36.00MTS DE FONDO Y CONTRAFONDO POR 28.37MTS X 16.82MTS DE FRENTE Y CONTRAFENTRE, AFECTA LA FIGURA DE UN POLIGONO IRREGULAR. TIENE TITULO DE PROPIEDAD, LISTA PARA ESCRITURAR. EL INMUEBLE CONSTA DE: UNA VIVIENDA UNIFAMILIAR DE 8.5 MTS DE FRENTE POR 7.5 MTS DE FONDO CON 2 DORMITORIOS, COCINA Y COMEDOR INTEGRADO, LIVING Y UN BAÑO EN LA PARTE DE ATRÁS DE LA VIVIENDA CONSTA DE UNA TERCERA HABITACIÓN DESTINADA A DEPÓSITO, TECHO DE CHAPAS DE ZINC, CIELORRASO DE MACHIMBRE, MUROS INTERIORES DE LADRILLOS, ABERTURAS DE ALUMINIO Y DE MADERA CUENTAN CON TODOS LOS SERVICIOS QUE HAY EN LA LOCALIDAD UBICADO EN UNA ZONA MUY IMPORTANTE DE LA LOCALIDAD DE SAN VICENTE A 100 MTS DEL COMANDO DE POLICIA Y DEL SEMAFORO DE LA RUTA NA 14, A 200 MTS DE LA RUTA NA 14, A 300 MTS DE LA MUNICIPALIDAD, A CUADRAS DEL JUZGADO Y DE LA ZONA DE BANCOS, A 700 MTS DE LA TERMINAL DE OMNIBUS, ESCUELAS, SUPERMERCADOS, CENTRO DE DIAGNOSTICOS, CERCA DE BARRIOS PRIVADOS SE ACEPTA PERMUTAR POR VEHICULO DE INTERES DEL PROPIETARIO Y COMO PARTE DE PAGO.',
        portada: portada8,
        vendido: false,
        cantImg: 10
      },
      {
        name: 'Lote de 2 Hectáreas en Eldorado, Misiones',
        text: 'IDEAL PARA UN EMPRENDIMIENTO TURÍSTICO GRACIAS A SUS CARACTERÍSTICAS NATURALES. VIVIENDA UNIFAMILIAR: CONSTA DE DOS HABITACIONES, LIVING-COMEDOR, BAÑO Y GALERÍA LOS DOS DORMITORIOS SE ENCUENTRAN CUBIERTOS CON PISO PARQUÈ Y CON PLACARES DE MADERA EN EXCELENTE ESTADO EL PREDIO CUENTA CON 2 HECTÁREAS (20000M²) CON UN CURSO DE AGUA QUE ATRAVIESA EL SECTOR ESTE Y UNA IMPORTANTE ARBOLEDA CON ESPECIES NATIVAS E IMPLANTADAS. ACCESO INMEDIATO A LA COSTANERA DE LA CIUDAD CUENTA CON TODOS LOS SERVICIOS SE ENCUENTRA SOBRE LA AVENIDA PRINCIPAL (EN EL KM 1 DE LA CIUDAD DE ELDORADO) Y A ESCASOS 300 MTS DE LA COSTANERA DE LA CIUDAD. TITULO DE PROPIEDAD, LISTA PARA TRANSFERIR.-',
        portada: portada9,
        vendido: false,
        cantImg: 12
      },
      {
        name: 'Lote en Villalonga, Garupá, Misiones',
        text: '',
        portada: portada10,
        vendido: true,
        cantImg: 9
      },
      {
        name: 'Cancha de futbol 5 + salon multiuso + Departamentos, Garupá, Misiones',
        text: '',
        portada: portada11,
        vendido: true,
        cantImg: 10
      }
    ]
  )

  const context = { propiedades }
  return (
    <div className='flex flex-col h-screen justify-between'>
      <Nav propiedades={propiedades} />
      <main className='mb-auto'>
        <Outlet context={context} />
      </main>
      <Footer />
    </div>
  )
}

export default Main
